# Models and DB utilities — imported directly from ratis_core
# Schemas — always imported from ratis_core.schemas to avoid name collisions
# (e.g. PriceChallengeResponse exists in both models and schemas)
#
# Usage:
#   from ratis_core.models import User, Scan, Product
#   from ratis_core.schemas import ScanCreate, ProductResponse
#   from ratis_core.database import get_db

from ratis_core.database import Base, SessionLocal, engine, get_db
from ratis_core.models import (
    AffiliateOffer,
    Badge,
    CabecoinsTransaction,
    CashbackTransaction,
    CashbackWithdrawal,
    Category,
    DiscountCampaign,
    LeaderboardSnapshot,
    LevelTier,
    NotificationLog,
    OptimizedRoute,
    PriceAlert,
    PriceChallenge,
    PriceChallengeResponse,
    PriceConsensus,
    PriceConsensusHistory,
    PriceConsensusScans,
    Product,
    ProductTracking,
    Receipt,
    RewardConfig,
    Scan,
    ShoppingList,
    ShoppingListItem,
    Store,
    StreakTier,
    Subscription,
    User,
    UserBadge,
    UserCabBalance,
    UserCashbackBalance,
    UserPreferences,
    UserPushToken,
    UserSession,
    UserSessionStat,
    UserStorePreference,
    UserStreak,
)

__all__ = [
    # Models
    "AffiliateOffer",
    "Badge",
    # Database
    "Base",
    "CabecoinsTransaction",
    "CashbackTransaction",
    "CashbackWithdrawal",
    "Category",
    "DiscountCampaign",
    "LeaderboardSnapshot",
    "LevelTier",
    "NotificationLog",
    "OptimizedRoute",
    "PriceAlert",
    "PriceChallenge",
    "PriceChallengeResponse",
    "PriceConsensus",
    "PriceConsensusHistory",
    "PriceConsensusScans",
    "Product",
    "ProductTracking",
    "Receipt",
    "RewardConfig",
    "Scan",
    "SessionLocal",
    "ShoppingList",
    "ShoppingListItem",
    "Store",
    "StreakTier",
    "Subscription",
    "User",
    "UserBadge",
    "UserCabBalance",
    "UserCashbackBalance",
    "UserPreferences",
    "UserPushToken",
    "UserSession",
    "UserSessionStat",
    "UserStorePreference",
    "UserStreak",
    "engine",
    "get_db",
]
