#!/usr/bin/env bash
# update-scripts-help.sh — regenerate OPS_SCRIPTS.md from each script's --help.
#
# Calls <script>.sh --help on every ops script in scripts/ops/ and concatenates
# the output into a single markdown file. Keeps the doc in sync with the code.
#
# Usage : ./scripts/ops/update-scripts-help.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../ops_lib.sh
source "$SCRIPT_DIR/../ops_lib.sh"

print_help() {
  cat <<EOF
update-scripts-help.sh — regenerate OPS_SCRIPTS.md.

Usage : ./scripts/ops/update-scripts-help.sh [--help]

Reads --help output from every ops script in scripts/ops/ and writes OPS_SCRIPTS.md.
EOF
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  print_help
  exit 0
fi

REPO_ROOT="$(repo_root)"
cd "$REPO_ROOT"

# Order matters for the doc — keep deploy/migrate first (most critical).
SCRIPTS=(
  "deploy-prod.sh"
  "migrate-prod.sh"
  "ota-push.sh"
  "eas-build.sh"
  "scan-debug.sh"
  "last-receipts.sh"
  "prod-status.sh"
  "update-scripts-help.sh"
)

OUT="$REPO_ROOT/docs/ops/OPS_SCRIPTS.md"
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

{
  cat <<HEADER
# OPS_SCRIPTS.md — operator scripts in scripts/ops/

Auto-generated by \`./scripts/ops/update-scripts-help.sh\` on $TS. Do not edit by hand.
This catalogue lives in \`docs/ops/\` ; the scripts themselves live in \`scripts/ops/\`.

Each script lives in \`scripts/ops/\` and is a self-contained \`bash\` operation
(\`set -euo pipefail\`). All long-running prod commands SSH into the Hetzner VM
(\`46.225.63.79\`, \`/root/ratis\`) using \`~/.ssh/ratis_hetzner_v3\`. Common helpers
live in \`scripts/ops_lib.sh\`.

Conventions :
- \`--help\` / \`-h\` on every script prints usage and exits 0.
- Errors abort with a non-zero exit and a clear stderr message.
- \`NO_COLOR=1\` disables ANSI codes. \`RATIS_YES=1\` skips Y/N confirms.
- Env overrides : \`PROD_HOST\`, \`PROD_USER\`, \`PROD_DIR\`, \`SSH_KEY\`.

## Scripts

| Script | One-liner |
|---|---|
| [deploy-prod.sh](../../scripts/ops/deploy-prod.sh) | Pull main + rebuild + restart product_analyser on prod |
| [migrate-prod.sh](../../scripts/ops/migrate-prod.sh) | Run alembic upgrade head on prod (uses migrations profile if present) |
| [ota-push.sh](../../scripts/ops/ota-push.sh) | \`eas update\` with channel-match guard against last APK |
| [eas-build.sh](../../scripts/ops/eas-build.sh) | Start an Android EAS build (preview/production) |
| [scan-debug.sh](../../scripts/ops/scan-debug.sh) | Render admin debug HTML + worker logs for a receipt |
| [last-receipts.sh](../../scripts/ops/last-receipts.sh) | Show 5 most recent receipts on prod |
| [prod-status.sh](../../scripts/ops/prod-status.sh) | docker ps + alembic version + today's activity counts |
| [update-scripts-help.sh](../../scripts/ops/update-scripts-help.sh) | Regenerate this file |

HEADER

  for s in "${SCRIPTS[@]}"; do
    if [[ ! -x "$REPO_ROOT/scripts/ops/$s" ]]; then
      warn "Script $s missing or not executable — skipping in doc"
      continue
    fi
    echo
    echo "## \`$s\`"
    echo
    echo '```'
    # Each script's --help must NOT make any network call (SSH / HTTP). They
    # exit early when --help is detected, so this is safe.
    "$REPO_ROOT/scripts/ops/$s" --help 2>&1 || true
    echo '```'
  done
} > "$OUT"

ok "Wrote $OUT ($(wc -c < "$OUT" | tr -d '[:space:]') bytes)"
