"""In-memory parser for ``ARCH_INVENTORY.md`` — used by the `docs_*` MCP tools.

The inventory file is auto-generated by `scripts/generate-arch-inventory.py`
and follows a strict pipe-separated convention :

    ID | STATUT | file:line | tags (espace-separated) | TL;DR

This module turns those lines into typed :class:`Entry` objects, with a
short-lived in-memory cache (TTL 60 s) so repeated tool calls don't
re-parse the whole file.

Design choices
--------------
* No regex backtracking — we split on ``" | "`` with a strict count of 5
  cells. Anything else is skipped (header rules ``---+---`` and any
  preamble lines that contain ``|`` like the column header).
* ``file:line`` is split on the *last* colon to be robust against paths
  that contain ``:`` (none today, but cheap insurance).
* Tags are split on whitespace into individual strings.
* Cache TTL is small enough that `python scripts/generate-arch-inventory.py`
  (followed by another tool call) reflects fresh data within a minute,
  but large enough that a search burst doesn't re-IO the file.

Path resolution
---------------
We compute the repo root relative to this module : 5 parents up
(``tools/agent-mcp/src/agent_mcp/tools/docs_index.py`` → repo root). The
inventory then lives at ``<repo_root>/docs/reference/ARCH_INVENTORY.md``.
The inventory path can be overridden via env var
``RATIS_DOCS_INVENTORY_PATH`` — used by tests to point at synthetic
inventories on tmpdir.

Note : the repo root is derived *independently* from the inventory
location (both flow from the same computed ``parents[5]``), so moving the
inventory under ``docs/reference/`` does not corrupt the resolution of the
other repo-root-relative sources in :data:`DEFAULT_SOURCES`. The one
exception is the test override : when ``RATIS_DOCS_INVENTORY_PATH`` is set,
the repo root falls back to the inventory's parent so synthetic test repos
(which drop ``ARCH_INVENTORY.md`` + ``docs/...`` at tmp-root) keep working.
"""

from __future__ import annotations

import glob
import os
import re
import time
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

# Module-level lazy import of Pydantic — we share BaseModel with the public
# tool surface for typed schemas (DA-49). Keep it module-local so tests can
# import this file without paying the cost twice.
from pydantic import BaseModel

# -- typed surface --------------------------------------------------------


class Entry(BaseModel):
    """One row of the inventory — matches what `docs_search` returns.

    The base fields (``id``, ``status``, ``file_path``, ``line``, ``tags``,
    ``tldr``) describe an inventory row. The multi-source extension adds
    optional fields populated by the alternate parsers (postmortems, skills,
    decisions, known problems, MEMORY) so the same hybrid search can run
    over the full corpus.
    """

    id: str
    """Section identifier (e.g. ``DA-11``, ``HSP-3``, ``ARCH_AUTH``)."""

    status: str
    """Free-form status — ``LIVRÉ V1.1``, ``EN-COURS``, ``PLANIFIÉ``, ..."""

    file_path: str
    """Repo-relative path of the source file (e.g. ``docs/arch/ARCH_geo.md``)."""

    line: int
    """1-indexed line number of the header in :attr:`file_path`."""

    tags: list[str] = []
    """Individual tag strings — split on whitespace from the inventory cell."""

    tldr: str
    """One-line summary copied from the inventory."""

    source: str = "arch_inventory"
    """Name of the :class:`IndexSource` that produced this entry. Defaults
    to ``"arch_inventory"`` so existing rows keep their semantics."""

    indexed_at: str | None = None
    """ISO-8601 timestamp captured when the entry was parsed. Optional for
    parsers that don't carry a meaningful date (typically the inventory)."""


class Section(BaseModel):
    """One section body returned by `docs_get` — adds raw markdown to ``Entry``."""

    id: str
    status: str
    file_path: str
    line: int
    tags: list[str] = []
    tldr: str
    body: str
    """Raw markdown of the section, header inclusive, no trailing newline."""


class FileInfo(BaseModel):
    """One file summary returned by `docs_list_files`."""

    path: str
    """Repo-relative path."""

    category: str
    """Coarse bucket : ``arch``, ``known``, ``decisions``, ``service-arch``,
    ``batch-arch``. Computed from the path prefix and the file name."""

    entries_count: int
    """Number of inventory entries pointing at this file."""


# -- cache state ----------------------------------------------------------


@dataclass
class _InventoryCache:
    """Mutable cache holder. Module-level singleton."""

    entries: list[Entry] = field(default_factory=list)
    loaded_at: float = 0.0
    source_path: Path | None = None


_CACHE = _InventoryCache()
CACHE_TTL_SECONDS = 60.0
"""How long a parsed inventory stays cached in-process."""


def _reset_cache_for_tests() -> None:
    """Test helper — drop the cached parse so the next call re-reads.

    Production code never needs this — the TTL handles freshness within the
    documented 60-second window.
    """
    _CACHE.entries = []
    _CACHE.loaded_at = 0.0
    _CACHE.source_path = None


# -- path resolution ------------------------------------------------------


def _default_repo_root() -> Path:
    """Repo root computed from this file's location, independent of the
    inventory path.

    Layout : ``<repo>/tools/agent-mcp/src/agent_mcp/tools/docs_index.py``,
    so 5 parents up = ``<repo>``.
    """
    return Path(__file__).resolve().parents[5]


def _default_inventory_path() -> Path:
    """``docs/reference/ARCH_INVENTORY.md`` computed from this file's location.

    The inventory moved out of the repo root into ``docs/reference/`` (the
    auto-generated index now lives alongside ``ENDPOINTS.md``). The repo root
    is still derived from :func:`_default_repo_root` so the *other*
    repo-root-relative sources resolve correctly.
    """
    return _default_repo_root() / "docs" / "reference" / "ARCH_INVENTORY.md"


def inventory_path() -> Path:
    """Resolve the inventory path with env-var override (used by tests)."""
    override = os.environ.get("RATIS_DOCS_INVENTORY_PATH")
    if override:
        return Path(override).expanduser()
    return _default_inventory_path()


# -- parsing --------------------------------------------------------------


def _parse_line(raw: str) -> Entry | None:
    """Parse one pipe-separated row. Return ``None`` on non-data rows.

    Accepts only lines with exactly 5 cells joined by `` | `` and a
    ``file:line`` cell where ``line`` is an integer. Header rows
    (``ID | STATUT | ...``) and rule rows (``---+---...``) naturally fail
    the integer check and are skipped silently.
    """
    line = raw.rstrip("\n")
    if " | " not in line:
        return None
    parts = line.split(" | ")
    if len(parts) != 5:
        return None
    raw_id, status, file_loc, tags_cell, tldr = (p.strip() for p in parts)
    if not raw_id or not status or not file_loc:
        return None
    # `file:line` — split on the last `:` to tolerate paths that contain it.
    if ":" not in file_loc:
        return None
    file_path, _, line_str = file_loc.rpartition(":")
    try:
        line_no = int(line_str)
    except ValueError:
        return None
    if line_no < 1:
        return None
    tags = tags_cell.split() if tags_cell else []
    return Entry(
        id=raw_id,
        status=status,
        file_path=file_path,
        line=line_no,
        tags=tags,
        tldr=tldr,
    )


def load_inventory(path: Path | None = None, *, force: bool = False) -> list[Entry]:
    """Read and parse ``ARCH_INVENTORY.md``, honouring the TTL cache.

    Args:
        path : Override the path (defaults to :func:`inventory_path`).
        force : Skip the cache for this call. Used by tests.

    Returns the list of :class:`Entry` in file order.
    """
    target = path or inventory_path()
    now = time.monotonic()
    cached_fresh = (
        not force and _CACHE.source_path == target and _CACHE.entries and (now - _CACHE.loaded_at) < CACHE_TTL_SECONDS
    )
    if cached_fresh:
        return _CACHE.entries

    if not target.exists():
        raise FileNotFoundError(
            f"ARCH_INVENTORY.md not found at {target}. Run `python scripts/generate-arch-inventory.py` to regenerate."
        )

    entries: list[Entry] = []
    text = target.read_text(encoding="utf-8")
    for raw in text.splitlines():
        parsed = _parse_line(raw)
        if parsed is not None:
            entries.append(parsed)

    _CACHE.entries = entries
    _CACHE.loaded_at = now
    _CACHE.source_path = target
    return entries


# =========================================================================
# Multi-source corpus (session-context-bridge extension)
# =========================================================================
#
# The original `load_inventory()` above remains the canonical loader for
# `ARCH_INVENTORY.md`. The multi-source machinery below builds on top —
# it indexes additional corpora (postmortems, skills, decisions ledger,
# known-problems entries, user MEMORY) so the same hybrid `docs_search`
# can serve the SessionStart context bridge.
#
# Backward compat : `Entry` keeps every original field. New parsers fill
# them with synthesised values (id from path stem, line=1, status="N/A"
# when there's no semantic status, etc.) and set `source` so callers can
# filter via `docs_search(sources=[...])`.

ParserFn = Callable[[Path], list[Entry]]
"""Signature shared by every multi-source parser. Returns a list of Entry."""


@dataclass(frozen=True)
class IndexSource:
    """One configurable entry into the multi-source corpus.

    ``glob_pattern`` is matched relative to the repo root (see
    :func:`_repo_root`) when it's not absolute. Absolute patterns are
    used as-is — that's how we point at ``~/.claude/postmortems/`` for
    per-user data. ``~`` is expanded.
    """

    name: str
    glob_pattern: str
    parser: ParserFn
    enabled: bool = True


# -- repo root helper -----------------------------------------------------


def _repo_root() -> Path:
    """Resolve the repo root used to expand repo-root-relative sources.

    Two regimes :

    * **Production** (no ``RATIS_DOCS_INVENTORY_PATH``) — the root is computed
      from this file's location (:func:`_default_repo_root`), *not* from the
      inventory's parent. The inventory now lives at
      ``docs/reference/ARCH_INVENTORY.md``, so its parent is ``docs/reference``
      — using it as the root would corrupt every other source path.
    * **Tests** (override set) — the root falls back to the inventory's parent,
      so a synthetic repo that drops ``ARCH_INVENTORY.md`` plus
      ``docs/decisions/...`` at tmp-root resolves all sources relative to that
      same tmp dir.
    """
    if os.environ.get("RATIS_DOCS_INVENTORY_PATH"):
        return inventory_path().parent
    return _default_repo_root()


def _resolve_glob(pattern: str) -> list[Path]:
    """Expand ``pattern`` against the repo root, honouring ``~``.

    Returns a sorted list of existing paths. Silent on misses — that's the
    point of "optional source" — the caller treats empty as "nothing to index".
    """
    expanded = os.path.expanduser(pattern)
    if os.path.isabs(expanded):
        target = expanded
    else:
        target = str(_repo_root() / expanded)
    matches = sorted(glob.glob(target))
    return [Path(m) for m in matches if Path(m).exists()]


def _now_iso() -> str:
    return datetime.now(UTC).isoformat()


# -- date helpers ---------------------------------------------------------

_DATE_FROM_FILENAME = re.compile(r"^(\d{4}-\d{2}-\d{2})")


def _iso_from_filename(path: Path) -> str | None:
    """Extract a ``YYYY-MM-DD`` date from the file stem, if any.

    Postmortems are named ``2026-05-05-78fcf9d8.md`` — pull the date prefix
    and emit it as midnight UTC ISO-8601 for the freshness filter.
    """
    m = _DATE_FROM_FILENAME.match(path.name)
    if not m:
        return None
    try:
        return datetime.strptime(m.group(1), "%Y-%m-%d").replace(tzinfo=UTC).isoformat()
    except ValueError:
        return None


def _iso_from_mtime(path: Path) -> str:
    """Fallback : file mtime as ISO-8601 UTC."""
    return datetime.fromtimestamp(path.stat().st_mtime, tz=UTC).isoformat()


def _relative_to_root(path: Path) -> str:
    """Repo-relative path if under the root, absolute as string otherwise."""
    root = _repo_root()
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path)


# -- parsers --------------------------------------------------------------


def parse_inventory(path: Path) -> list[Entry]:
    """Adapter — wraps the existing `_parse_line` loop into the parser
    protocol so ``ARCH_INVENTORY.md`` can sit alongside other sources.

    Unlike :func:`load_inventory` this version does NOT touch the cache —
    it's a pure file parser. The cache lives in :func:`load_corpus`.
    """
    if not path.exists():
        return []
    entries: list[Entry] = []
    text = path.read_text(encoding="utf-8")
    for raw in text.splitlines():
        parsed = _parse_line(raw)
        if parsed is not None:
            entries.append(parsed)
    return entries


def parse_decisions(path: Path) -> list[Entry]:
    """Parse ``DECISIONS_ACTED.md`` / ``DECISIONS_PENDING.md``.

    Convention : ``## DA-N — <title> · <refs> · <STATUT>`` followed by a
    ``> TL;DR`` line and an optional ``> @tags:`` line (cf R41).

    Returns one :class:`Entry` per H2 section. The ``id`` is the DA-N
    handle ; ``status`` is the trailing status segment ; ``tldr`` is the
    TL;DR quote-block line.
    """
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    return _parse_h2_sections(text, path, source_hint="decisions")


def parse_known_problems(path: Path) -> list[Entry]:
    """Parse ``KNOWN_PROBLEMS.md`` — H2 sections shaped ``## KP-N — title``.

    Same conventions as :func:`parse_decisions` — pipe-separated R41
    metadata in the title plus ``> TL;DR`` / ``> @tags:`` quote lines.
    """
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    return _parse_h2_sections(text, path, source_hint="known_problems")


def parse_postmortem(path: Path) -> list[Entry]:
    """Parse one postmortem markdown file.

    Postmortems live under ``~/.claude/postmortems/YYYY-MM-DD-<uuid>.md``.
    Each file is one entry — id = filename stem, tldr = first non-trivial
    line of the ``## Summary`` section.
    """
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    entry_id = path.stem
    summary = _extract_section(text, "Summary")
    outcome = _extract_section(text, "Outcome")
    tldr_candidate = _first_meaningful_line(summary) or _first_meaningful_line(outcome) or ""
    # Status : pull from the "Outcomes" line if present, else "postmortem".
    status = "postmortem"
    for line in outcome.splitlines():
        line = line.strip()
        if line.lower().startswith("- **outcomes**"):
            _, _, rest = line.partition(":")
            status = rest.strip() or "postmortem"
            break
    tags = _extract_postmortem_tags(text)
    indexed_at = _iso_from_filename(path) or _iso_from_mtime(path)
    return [
        Entry(
            id=entry_id,
            status=status,
            file_path=str(path),
            line=1,
            tags=tags,
            tldr=tldr_candidate[:200],
            source="postmortems",
            indexed_at=indexed_at,
        )
    ]


def parse_skill(path: Path) -> list[Entry]:
    """Parse a ``SKILL.md`` (active skill in ``.claude/skills/<n>/SKILL.md``).

    Returns one :class:`Entry`. ``id`` is the directory name (skill slug).
    Title + description come from the YAML frontmatter ; ``tags`` carry the
    word ``skill`` so consumers can filter via ``sources=["skills_active"]``.
    """
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    meta = _parse_yaml_frontmatter(text)
    skill_name = meta.get("name") or path.parent.name
    description = (meta.get("description") or "").strip()
    return [
        Entry(
            id=skill_name,
            status="active",
            file_path=_relative_to_root(path),
            line=1,
            tags=["skill"],
            tldr=description[:200],
            source="skills_active",
            indexed_at=_iso_from_mtime(path),
        )
    ]


def parse_skill_filter_reviewed(path: Path) -> list[Entry]:
    """Parse a reviewed candidate ``SKILL.md`` under ``.claude/skill-candidates/``.

    Only candidates whose frontmatter carries ``status: reviewed`` (or any
    truthy ``reviewed: true``) are kept. Drafts are NOT indexed so the
    session-context bridge doesn't surface noise.
    """
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    meta = _parse_yaml_frontmatter(text)
    status = (meta.get("status") or "").strip().lower()
    reviewed_flag = str(meta.get("reviewed") or "").strip().lower()
    if status != "reviewed" and reviewed_flag not in ("true", "yes", "1"):
        return []
    skill_name = meta.get("name") or path.parent.name
    description = (meta.get("description") or "").strip()
    return [
        Entry(
            id=skill_name,
            status="reviewed-candidate",
            file_path=_relative_to_root(path),
            line=1,
            tags=["skill", "candidate"],
            tldr=description[:200],
            source="skill_candidates_reviewed",
            indexed_at=_iso_from_mtime(path),
        )
    ]


def parse_user_memory(path: Path) -> list[Entry]:
    """Parse the user-level ``MEMORY.md`` index file.

    The MEMORY.md format is intentionally loose ; we extract one entry per
    Markdown bullet ``- [title](link) — note`` so each remembered fact is
    independently searchable.
    """
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    entries: list[Entry] = []
    bullet_re = re.compile(r"^-\s+\[([^\]]+)\]\(([^)]+)\)\s+—\s+(.+)$")
    for i, raw in enumerate(text.splitlines(), start=1):
        m = bullet_re.match(raw.strip())
        if not m:
            continue
        # `link` is captured by the regex but not used — we only surface
        # the title + note pair, the link points back at a local memory file
        # that the agent doesn't need to navigate.
        title = m.group(1)
        note = m.group(3)
        slug = re.sub(r"[^a-z0-9-]+", "-", title.lower()).strip("-") or f"memory-{i}"
        entries.append(
            Entry(
                id=f"MEM-{slug}",
                status="memory",
                file_path=str(path),
                line=i,
                tags=["memory", "user"],
                tldr=f"{title} — {note}"[:200],
                source="user_memory",
                indexed_at=None,  # MEMORY.md is timeless
            )
        )
    # Also surface the file itself as a coarse entry, so a query that does
    # not match a bullet still pulls the MEMORY index into context.
    if entries:
        entries.append(
            Entry(
                id="MEMORY_INDEX",
                status="memory",
                file_path=str(path),
                line=1,
                tags=["memory", "user", "index"],
                tldr="User-level long-term memory index.",
                source="user_memory",
                indexed_at=None,
            )
        )
    return entries


# -- shared helpers for the parsers --------------------------------------

_H2_HEADER_RE = re.compile(r"^##\s+([A-Z]+-\d+)\b\s*[—:-]?\s*(.*)$")
_STATUS_TAIL_RE = re.compile(r"·\s*([^·]+)$")


def _parse_h2_sections(text: str, path: Path, *, source_hint: str) -> list[Entry]:
    """Generic H2 section parser for decisions / known-problems.

    For each ``## ID-N — ...`` header :
    * id = the matched ``ID-N`` handle
    * status = last ``·``-separated cell after the title, fallback to ``""``
    * tldr = the first ``> ...`` quote-block line under the header
    * tags = whitespace-split from a ``> @tags: ...`` quote line, if any
    """
    lines = text.splitlines()
    out: list[Entry] = []
    for i, line in enumerate(lines, start=1):
        m = _H2_HEADER_RE.match(line)
        if not m:
            continue
        entry_id = m.group(1)
        title_rest = m.group(2)
        status = ""
        stat_m = _STATUS_TAIL_RE.search(title_rest)
        if stat_m:
            status = stat_m.group(1).strip()
        tldr = ""
        tags: list[str] = []
        # Look at the next ~8 lines for `> TL;DR` and `> @tags:` quote blocks.
        # STOP at the next `##` header so we don't leak tags between sections.
        for j in range(i, min(i + 8, len(lines))):
            raw = lines[j]
            stripped = raw.strip()
            if stripped.startswith("## "):
                break
            if not stripped.startswith(">"):
                continue
            body = stripped.lstrip("> ").strip()
            if body.lower().startswith("@tags"):
                _, _, after = body.partition(":")
                tags = after.split()
            elif not tldr and not body.startswith("@"):
                tldr = body
        out.append(
            Entry(
                id=entry_id,
                status=status or "N/A",
                file_path=_relative_to_root(path),
                line=i,
                tags=tags,
                tldr=tldr[:200],
                source=source_hint,
                indexed_at=_iso_from_mtime(path),
            )
        )
    return out


def _extract_section(text: str, heading: str) -> str:
    """Return the body of the ``## <heading>`` section, stopping at the next H2.

    Empty string if the heading isn't found. Heading match is case-insensitive
    and tolerates trailing whitespace.
    """
    lines = text.splitlines()
    needle = heading.strip().lower()
    out: list[str] = []
    inside = False
    for line in lines:
        if line.startswith("## "):
            if inside:
                break
            if line[3:].strip().lower() == needle:
                inside = True
                continue
        if inside:
            out.append(line)
    return "\n".join(out).strip()


def _first_meaningful_line(text: str) -> str:
    """First non-empty, non-list-bullet line — typical "summary" extraction."""
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("(") and line.endswith(")"):
            continue  # `(none reported by LLM — see raw stats below)` etc.
        # Bullets are OK as a fallback but prefer prose.
        return line.lstrip("- *").strip()
    return ""


def _extract_postmortem_tags(text: str) -> list[str]:
    """Collect a small tag set from `## Patterns observed` keywords + outcome."""
    tags: set[str] = {"postmortem"}
    patterns = _extract_section(text, "Patterns observed")
    # Each pattern starts with `- **<name>**` — capture the name slug.
    for line in patterns.splitlines():
        line = line.strip()
        if line.startswith("- **"):
            end = line.find("**", 4)
            if end > 4:
                slug = re.sub(r"[^a-z0-9-]+", "-", line[4:end].lower()).strip("-")
                if slug:
                    tags.add(slug[:40])
    return sorted(tags)


_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def _parse_yaml_frontmatter(text: str) -> dict[str, str]:
    """Tiny YAML-ish frontmatter parser — handles the simple ``key: value``
    and ``key: >- multi-line block`` forms used by ``SKILL.md``.

    NOT a full YAML parser. We deliberately avoid pulling PyYAML for this —
    the SKILL.md format is constrained, the failure mode is benign (empty
    description = empty tldr, the entry is still searchable by its id).
    """
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return {}
    body = m.group(1)
    meta: dict[str, str] = {}
    current_key: str | None = None
    folded_buf: list[str] = []
    for raw in body.splitlines():
        if not raw.strip():
            continue
        if not raw.startswith(" ") and ":" in raw:
            # flush any folded buffer
            if current_key is not None:
                meta[current_key] = " ".join(folded_buf).strip()
                folded_buf = []
                current_key = None
            key, _, value = raw.partition(":")
            key = key.strip()
            value = value.strip()
            if value in (">", ">-", "|", "|-"):
                current_key = key
                folded_buf = []
            else:
                meta[key] = value
        elif current_key is not None:
            folded_buf.append(raw.strip())
    if current_key is not None:
        meta[current_key] = " ".join(folded_buf).strip()
    return meta


# -- default sources & top-level loader ----------------------------------


DEFAULT_SOURCES: tuple[IndexSource, ...] = (
    IndexSource("arch_inventory", "docs/reference/ARCH_INVENTORY.md", parse_inventory),
    IndexSource("decisions_acted", "docs/decisions/DECISIONS_ACTED.md", parse_decisions),
    IndexSource("decisions_pending", "docs/decisions/DECISIONS_PENDING.md", parse_decisions),
    IndexSource("known_problems", "docs/known/KNOWN_PROBLEMS.md", parse_known_problems),
    IndexSource("postmortems", "~/.claude/postmortems/*.md", parse_postmortem),
    IndexSource("skills_active", ".claude/skills/*/SKILL.md", parse_skill),
    IndexSource(
        "skill_candidates_reviewed",
        ".claude/skill-candidates/*/SKILL.md",
        parse_skill_filter_reviewed,
    ),
    IndexSource(
        "user_memory",
        "~/.claude/projects/-Users-guillaume-Cursor-Ratis/memory/MEMORY.md",
        parse_user_memory,
    ),
)


@dataclass
class _CorpusCache:
    entries: list[Entry] = field(default_factory=list)
    loaded_at: float = 0.0
    sources_signature: tuple[str, ...] = ()


_CORPUS_CACHE = _CorpusCache()


def _reset_corpus_cache_for_tests() -> None:
    """Drop the multi-source corpus cache. Mirrors :func:`_reset_cache_for_tests`."""
    _CORPUS_CACHE.entries = []
    _CORPUS_CACHE.loaded_at = 0.0
    _CORPUS_CACHE.sources_signature = ()


def load_corpus(
    sources: list[IndexSource] | None = None,
    *,
    force: bool = False,
) -> list[Entry]:
    """Load every enabled :class:`IndexSource` and return the flattened entry list.

    Args:
        sources : custom source list — defaults to :data:`DEFAULT_SOURCES`.
            Tests typically pass a synthetic subset.
        force : skip the TTL cache for this call.

    Order of returned entries follows the order of ``sources`` (and inside
    each source, the order the parser emits). Cache key includes the source
    names so swapping sources between calls correctly invalidates.
    """
    pool = list(sources) if sources is not None else list(DEFAULT_SOURCES)
    enabled = [s for s in pool if s.enabled]
    signature = tuple(s.name for s in enabled)
    now = time.monotonic()
    cached_fresh = (
        not force
        and _CORPUS_CACHE.entries
        and _CORPUS_CACHE.sources_signature == signature
        and (now - _CORPUS_CACHE.loaded_at) < CACHE_TTL_SECONDS
    )
    if cached_fresh:
        return _CORPUS_CACHE.entries

    out: list[Entry] = []
    for src in enabled:
        for path in _resolve_glob(src.glob_pattern):
            try:
                entries = src.parser(path)
            except Exception:  # noqa: S112 — one bad file must not poison the corpus.
                continue
            # Defensive : ensure the parser stamped the source name.
            for e in entries:
                if e.source != src.name:
                    e_dict = e.model_dump()
                    e_dict["source"] = src.name
                    out.append(Entry(**e_dict))
                else:
                    out.append(e)

    _CORPUS_CACHE.entries = out
    _CORPUS_CACHE.loaded_at = now
    _CORPUS_CACHE.sources_signature = signature
    return out
