"""add R2 image columns to receipts

Revision ID: 28974f35fb76
Revises: b3e7f9a21c4d
Create Date: 2026-04-05 12:58:28.119908+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28974f35fb76'
down_revision: Union[str, None] = 'b3e7f9a21c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('image_r2_key', sa.Text(), nullable=True))
    op.add_column('receipts', sa.Column('image_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('receipts', sa.Column('image_deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'image_deleted_at')
    op.drop_column('receipts', 'image_uploaded_at')
    op.drop_column('receipts', 'image_r2_key')
    # ### end Alembic commands ###
