"""Feed Jack — rework user_streaks + new CAB reasons (food_reserve_purchase, streak_repair)

Revision ID: g9h0i1j2k3l4
Revises: f8a9b0c1d2e3
Create Date: 2026-04-14 14:00:00

Changes:
  1. user_streaks table — DROP old columns (daily_streak*, weekly_streak*, last_login_date,
     last_scan_week, last_scan_year) and all related CHECK constraints.
     ADD new Feed Jack columns: current_streak_days, last_fed_at, food_reserves, timezone.
  2. cabecoin_transactions_reason_check constraint — add 'food_reserve_purchase' and
     'streak_repair' as valid CAB debit reasons.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "g9h0i1j2k3l4"
down_revision = "f8a9b0c1d2e3"
branch_labels = None
depends_on = None


# Full ordered list of CAB reasons after migration (keep in sync with VALID_REASONS / DA-04)
_CAB_REASONS_AFTER = (
    "receipt_scan",
    "label_scan",
    "barcode_scan",
    "mission_reward",
    "battlepass_milestone",
    "referral",
    "cashback_boost_debit",
    "cashback_boost_refund",
    "shop_purchase",
    "stonks_boost",
    "mission_freeze",
    "food_reserve_purchase",  # new — Feed Jack
    "streak_repair",          # new — Feed Jack
)

_CAB_REASONS_BEFORE = (
    "receipt_scan",
    "label_scan",
    "barcode_scan",
    "mission_reward",
    "battlepass_milestone",
    "referral",
    "cashback_boost_debit",
    "cashback_boost_refund",
    "shop_purchase",
    "stonks_boost",
    "mission_freeze",
)


def _reason_check(reasons: tuple[str, ...]) -> str:
    values = ", ".join(f"'{r}'" for r in reasons)
    return f"reason IN ({values})"


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 1. user_streaks — drop old constraints + old columns, add new ones
    # ------------------------------------------------------------------

    # Drop old CHECK constraints (they reference columns we're about to drop).
    # Use IF EXISTS + both possible names: the initial migration named them
    # explicitly (daily_streak_nn / weekly_streak_nn) but some dev databases
    # have PostgreSQL-autogenerated names (user_streaks_*_check). Both are safe
    # to attempt — the IF EXISTS guard makes this idempotent on either schema.
    op.execute("ALTER TABLE user_streaks DROP CONSTRAINT IF EXISTS user_streaks_daily_streak_check")
    op.execute("ALTER TABLE user_streaks DROP CONSTRAINT IF EXISTS daily_streak_nn")
    op.execute("ALTER TABLE user_streaks DROP CONSTRAINT IF EXISTS user_streaks_weekly_streak_check")
    op.execute("ALTER TABLE user_streaks DROP CONSTRAINT IF EXISTS weekly_streak_nn")
    op.execute("ALTER TABLE user_streaks DROP CONSTRAINT IF EXISTS best_gte_current")
    op.execute("ALTER TABLE user_streaks DROP CONSTRAINT IF EXISTS scan_week_coherence")
    op.execute("ALTER TABLE user_streaks DROP CONSTRAINT IF EXISTS scan_week_range")

    # Drop old columns
    op.drop_column("user_streaks", "daily_streak")
    op.drop_column("user_streaks", "daily_streak_best")
    op.drop_column("user_streaks", "last_login_date")
    op.drop_column("user_streaks", "weekly_streak")
    op.drop_column("user_streaks", "weekly_streak_best")
    op.drop_column("user_streaks", "last_scan_week")
    op.drop_column("user_streaks", "last_scan_year")

    # Add new Feed Jack columns
    op.add_column(
        "user_streaks",
        sa.Column(
            "current_streak_days",
            sa.Integer,
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "user_streaks",
        sa.Column("last_fed_at", sa.Date, nullable=True),
    )
    op.add_column(
        "user_streaks",
        sa.Column(
            "food_reserves",
            sa.Integer,
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "user_streaks",
        sa.Column(
            "timezone",
            sa.Text,
            nullable=False,
            server_default="Europe/Paris",
        ),
    )

    # New CHECK constraints
    op.create_check_constraint(
        "user_streaks_streak_days_nn",
        "user_streaks",
        "current_streak_days >= 0",
    )
    op.create_check_constraint(
        "user_streaks_food_reserves_nn",
        "user_streaks",
        "food_reserves >= 0",
    )

    # ------------------------------------------------------------------
    # 2. cabecoin_transactions — extend reason CHECK constraint
    # ------------------------------------------------------------------
    op.drop_constraint(
        "cabecoin_transactions_reason_check",
        "cabecoin_transactions",
        type_="check",
    )
    op.create_check_constraint(
        "cabecoin_transactions_reason_check",
        "cabecoin_transactions",
        _reason_check(_CAB_REASONS_AFTER),
    )


def downgrade() -> None:
    # ------------------------------------------------------------------
    # 2. cabecoin_transactions — revert reason constraint
    # ------------------------------------------------------------------
    # Cannot downgrade if food_reserve_purchase / streak_repair rows exist
    op.drop_constraint(
        "cabecoin_transactions_reason_check",
        "cabecoin_transactions",
        type_="check",
    )
    op.create_check_constraint(
        "cabecoin_transactions_reason_check",
        "cabecoin_transactions",
        _reason_check(_CAB_REASONS_BEFORE),
    )

    # ------------------------------------------------------------------
    # 1. user_streaks — restore old schema
    # ------------------------------------------------------------------
    op.drop_constraint("user_streaks_streak_days_nn", "user_streaks", type_="check")
    op.drop_constraint("user_streaks_food_reserves_nn", "user_streaks", type_="check")

    op.drop_column("user_streaks", "current_streak_days")
    op.drop_column("user_streaks", "last_fed_at")
    op.drop_column("user_streaks", "food_reserves")
    op.drop_column("user_streaks", "timezone")

    op.add_column(
        "user_streaks",
        sa.Column("daily_streak", sa.Integer, nullable=False, server_default="0"),
    )
    op.add_column(
        "user_streaks",
        sa.Column("daily_streak_best", sa.Integer, nullable=False, server_default="0"),
    )
    op.add_column(
        "user_streaks",
        sa.Column("last_login_date", sa.Date, nullable=True),
    )
    op.add_column(
        "user_streaks",
        sa.Column("weekly_streak", sa.Integer, nullable=False, server_default="0"),
    )
    op.add_column(
        "user_streaks",
        sa.Column("weekly_streak_best", sa.Integer, nullable=False, server_default="0"),
    )
    op.add_column(
        "user_streaks",
        sa.Column("last_scan_week", sa.Integer, nullable=True),
    )
    op.add_column(
        "user_streaks",
        sa.Column("last_scan_year", sa.Integer, nullable=True),
    )

    op.create_check_constraint("daily_streak_nn", "user_streaks", "daily_streak >= 0")
    op.create_check_constraint("weekly_streak_nn", "user_streaks", "weekly_streak >= 0")
    op.create_check_constraint(
        "best_gte_current",
        "user_streaks",
        "daily_streak_best >= daily_streak AND weekly_streak_best >= weekly_streak",
    )
    op.create_check_constraint(
        "scan_week_coherence",
        "user_streaks",
        "(last_scan_week IS NULL AND last_scan_year IS NULL) OR "
        "(last_scan_week IS NOT NULL AND last_scan_year IS NOT NULL)",
    )
    op.create_check_constraint(
        "scan_week_range",
        "user_streaks",
        "last_scan_week IS NULL OR last_scan_week BETWEEN 1 AND 53",
    )
