"""add_product_fields_and_batch_sync_log

Revision ID: 3fc211df1a2d
Revises: 9bac37ba78e4
Create Date: 2026-04-04 13:07:18.528540+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fc211df1a2d'
down_revision: Union[str, None] = '9bac37ba78e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_sync_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_name', sa.Text(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('rows_affected', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('product_quantity', sa.Numeric(), nullable=True))
    op.add_column('products', sa.Column('product_quantity_unit', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('quantity_raw', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('storage_type', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('allergens_tags', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('products', sa.Column('ingredients_tags', postgresql.ARRAY(sa.Text()), nullable=True))
    op.create_index('ix_batch_sync_log_batch_name', 'batch_sync_log', ['batch_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ingredients_tags')
    op.drop_column('products', 'allergens_tags')
    op.drop_column('products', 'storage_type')
    op.drop_column('products', 'quantity_raw')
    op.drop_column('products', 'product_quantity_unit')
    op.drop_column('products', 'product_quantity')
    op.drop_index('ix_batch_sync_log_batch_name', table_name='batch_sync_log')
    op.drop_table('batch_sync_log')
    # ### end Alembic commands ###
