"""add_brands_photo_url_small_to_products

Revision ID: f0076591d228
Revises: 3fc211df1a2d
Create Date: 2026-04-04 13:38:08.251637+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0076591d228'
down_revision: Union[str, None] = '3fc211df1a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brands', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('photo_url_small', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'photo_url_small')
    op.drop_column('products', 'brands')
    # ### end Alembic commands ###
