"""drop_price_consensus_history_scans

Revision ID: f4e3cd849eae
Revises: a2f8b9c1d3e5
Create Date: 2026-04-06 14:53:39.480094+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e3cd849eae'
down_revision: Union[str, None] = 'a2f8b9c1d3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_consensus_history_scans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_consensus_history_scans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('history_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['price_consensus_history.id'], name=op.f('fk_history'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scan'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('price_consensus_history_scans_pkey')),
    sa.UniqueConstraint('history_id', 'scan_id', name=op.f('price_consensus_history_scans_history_id_scan_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
