"""SIRENE Parquet parser — streaming, chunked, APE-filtered.

Reads the ``StockEtablissement_utf8.parquet`` file produced by
``download.ensure_dump()`` and yields rows as ``dict`` objects, applying:

- **APE code filter** : only rows whose ``activitePrincipaleEtablissement``
  is in ``ape_whitelist`` are yielded.
- **State filter** : by default ``include_closed=True`` yields all rows
  (both ``'A'`` = actif and ``'F'`` = fermé); set ``include_closed=False``
  to restrict to active establishments only.
- **Memory-safe streaming** : uses ``pq.ParquetFile.iter_batches()`` to
  avoid loading the full dump (>10 M rows) into RAM.

Audit F-12 — row_group_size and iter_batches()
----------------------------------------------
``pq.ParquetFile.iter_batches(batch_size=N)`` does NOT guarantee batches of
exactly N rows.  It iterates over the file's row groups; if each row group
contains K rows, you get K-row batches regardless of ``batch_size``.

The Parquet file generated by ``download._convert_csv_to_parquet()`` is
written with ``row_group_size=5000`` (same as the default ``chunk_size``
here).  This alignment ensures that ``iter_batches(batch_size=chunk_size)``
yields batches of ~5000 rows as expected.  If you use a different
``chunk_size`` here without regenerating the file, batch sizes will be
governed by the file's row groups (5000), not by your ``chunk_size`` argument.

APE code normalisation
----------------------
INSEE dumps can write APE codes *with* or *without* the decimal point:
``'47.11B'`` and ``'4711B'`` represent the same code.  Both forms are
normalised before comparison so the whitelist (which uses the dotted form)
matches either variant:

    normalise('47.11B') → '4711B'
    normalise('4711B')  → '4711B'

The whitelist is also normalised at parser construction time.
"""

from __future__ import annotations

import logging
from collections.abc import Iterator
from pathlib import Path

import pyarrow.parquet as pq

_log = logging.getLogger(__name__)

# SIRENE column names for APE code and administrative state.
_COL_APE = "activitePrincipaleEtablissement"
_COL_STATE = "etatAdministratifEtablissement"


def _normalize_ape(code: str | None) -> str:
    """Normalise an APE code to its no-dot form for comparison.

    >>> _normalize_ape('47.11B')
    '4711B'
    >>> _normalize_ape('4711B')
    '4711B'
    >>> _normalize_ape(None)
    ''
    """
    if not code:
        return ""
    return (code or "").replace(".", "").strip().upper()


def stream_etablissements(
    parquet_path: Path,
    *,
    ape_whitelist: list[str],
    chunk_size: int = 5000,
    include_closed: bool = True,
) -> Iterator[dict]:
    """Yield filtered SIRENE rows as dicts, streaming from a Parquet file.

    Parameters
    ----------
    parquet_path:
        Path to ``StockEtablissement_utf8.parquet`` (produced by
        ``download.ensure_dump()``).
    ape_whitelist:
        List of APE codes to keep (e.g. ``['47.11B', '47.21Z', ...]``).
        Codes are normalised (dot stripped) before comparison, so the list
        may use either form.
    chunk_size:
        ``batch_size`` hint passed to ``iter_batches()`` — see the F-12 note
        in the module docstring.  Should match the ``row_group_size`` used
        when writing the Parquet file (default 5000).
    include_closed:
        When ``True`` (default), yield both active (``'A'``) and closed
        (``'F'``) establishments.  Set to ``False`` to restrict to active
        only.

    Yields
    ------
    dict
        One dict per matching row.  Keys are the Parquet column names (raw
        SIRENE field names).  Values are Python scalars (strings, None).
    """
    parquet_path = Path(parquet_path)
    # Normalise whitelist once.
    whitelist_set = {_normalize_ape(code) for code in ape_whitelist}
    _log.info(
        "stream_etablissements: opening %s (chunk_size=%d, include_closed=%s, whitelist=%d codes)",
        parquet_path,
        chunk_size,
        include_closed,
        len(whitelist_set),
    )

    pf = pq.ParquetFile(str(parquet_path))
    total_yielded = 0
    total_scanned = 0

    for batch in pf.iter_batches(batch_size=chunk_size):
        # Convert the RecordBatch to a Python dict of column → list of values
        # for vectorised pre-filtering.
        col_ape = batch.column(_COL_APE).to_pylist() if _COL_APE in batch.schema.names else [None] * len(batch)
        col_state = batch.column(_COL_STATE).to_pylist() if _COL_STATE in batch.schema.names else [None] * len(batch)

        n_rows = len(batch)
        total_scanned += n_rows

        # Build the full row dict lazily (only for passing rows).
        col_names = batch.schema.names
        columns = {name: batch.column(name).to_pylist() for name in col_names}

        for i in range(n_rows):
            ape_raw = col_ape[i]
            if _normalize_ape(ape_raw) not in whitelist_set:
                continue
            state = col_state[i]
            if not include_closed and state != "A":
                continue
            row = {name: columns[name][i] for name in col_names}
            total_yielded += 1
            yield row

    _log.info(
        "stream_etablissements: done — scanned=%d, yielded=%d",
        total_scanned,
        total_yielded,
    )
