"""Tests for sirene_sync.parser — stream_etablissements() APE filter + streaming.

Uses the synthetic fixture at tests/fixtures/stock_etab_sample.parquet.

Fixture composition (from _generate_sample.py):
  - 30 active food APE ('A'): 10×47.11B + 10×47.11D + 10×47.21Z
  - 10 closed food APE ('F'): 47.11B, 5 with date + 5 without
  - 10 non-food active ('A'): 47.51Z (textile)
  -  5 active food: enseigne1=None (fallback to denomination)
  -  5 active food: numeroVoie=None (partial address)
  - 40 active food with varied APE (47.22Z, 47.29Z, etc.)
  Total: 100 rows

Food APE = any in sirene_sync.ape_whitelist (47.11A-F, 47.21Z, etc.)
The 47.51Z rows are the only non-food APE.
"""

from __future__ import annotations

from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq
import pytest

FIXTURE_DIR = Path(__file__).parent / "fixtures"
SAMPLE_PARQUET = FIXTURE_DIR / "stock_etab_sample.parquet"

# APE whitelist from ratis_settings.json sirene_sync section.
APE_WHITELIST = [
    "47.11A",
    "47.11B",
    "47.11C",
    "47.11D",
    "47.11E",
    "47.11F",
    "47.21Z",
    "47.22Z",
    "47.23Z",
    "47.24Z",
    "47.25Z",
    "47.29Z",
    "47.81Z",
]


@pytest.fixture(scope="module")
def sample_parquet(tmp_path_factory):
    """Ensure the fixture Parquet is present (generated by _generate_sample.py)."""
    if not SAMPLE_PARQUET.exists():
        pytest.skip(
            f"Fixture not found: {SAMPLE_PARQUET}. "
            "Run batch/ratis_batch_sirene_sync/tests/fixtures/_generate_sample.py first."
        )
    return SAMPLE_PARQUET


class TestStreamEtablissements:
    def test_parser_filters_ape_whitelist(self, sample_parquet):
        """Active food rows only (30 'A' with whitelist APE) when include_closed=False."""
        from sirene_sync.parser import stream_etablissements

        rows = list(
            stream_etablissements(
                sample_parquet,
                ape_whitelist=APE_WHITELIST,
                include_closed=False,
            )
        )
        # Active food rows: 30 (10×47.11B + 10×47.11D + 10×47.21Z)
        # + 5 (enseigne NULL) + 5 (numeroVoie NULL) = 40 + varied APE
        # Total active food = all rows with APE in whitelist and state='A'
        # Non-food (47.51Z) should be excluded.
        ape_values = {r["activitePrincipaleEtablissement"] for r in rows}
        assert "47.51Z" not in ape_values, "Non-food APE must be excluded"
        # All yielded rows must be active.
        states = {r["etatAdministratifEtablissement"] for r in rows}
        assert states == {"A"}, f"Expected only active rows, got states: {states}"

    def test_parser_includes_closed_when_flag_set(self, sample_parquet):
        """include_closed=True yields both 'A' and 'F' rows."""
        from sirene_sync.parser import stream_etablissements

        rows_active_only = list(
            stream_etablissements(
                sample_parquet,
                ape_whitelist=APE_WHITELIST,
                include_closed=False,
            )
        )
        rows_all = list(
            stream_etablissements(
                sample_parquet,
                ape_whitelist=APE_WHITELIST,
                include_closed=True,
            )
        )
        # include_closed=True should yield more rows (the 10 closed food ones).
        assert len(rows_all) > len(rows_active_only)
        states_all = {r["etatAdministratifEtablissement"] for r in rows_all}
        assert "F" in states_all, "Closed rows must be present with include_closed=True"

    def test_parser_excludes_non_food(self, sample_parquet):
        """47.51Z textile rows must never appear regardless of include_closed."""
        from sirene_sync.parser import stream_etablissements

        for include_closed in (True, False):
            rows = list(
                stream_etablissements(
                    sample_parquet,
                    ape_whitelist=APE_WHITELIST,
                    include_closed=include_closed,
                )
            )
            non_food = [r for r in rows if r["activitePrincipaleEtablissement"] == "47.51Z"]
            assert non_food == [], f"Non-food 47.51Z found with include_closed={include_closed}"

    def test_parser_streams_chunked(self, sample_parquet):
        """The generator must yield incrementally, not load everything into RAM.

        We verify by counting the number of batches internally: with 100 rows
        and row_group_size=50 (set in _generate_sample.py), iter_batches should
        produce ≥ 2 batches.
        """
        import pyarrow.parquet as pq_lib

        # Count actual row groups in fixture.
        pf = pq_lib.ParquetFile(str(sample_parquet))
        n_row_groups = pf.metadata.num_row_groups
        assert n_row_groups >= 2, f"Fixture should have ≥2 row groups for chunked streaming test, got {n_row_groups}"

        # Stream and verify generator laziness by counting batch steps.
        from sirene_sync.parser import stream_etablissements

        gen = stream_etablissements(
            sample_parquet,
            ape_whitelist=APE_WHITELIST,
            include_closed=True,
        )
        # Consume all rows — the generator must produce them correctly.
        rows = list(gen)
        assert len(rows) > 0

    def test_parser_normalizes_ape_codes(self, tmp_path):
        """APE codes with AND without dots must both match the whitelist.

        Creates a small Parquet with codes in both formats and verifies
        that stream_etablissements() accepts both.
        """
        from sirene_sync.parser import stream_etablissements

        # Build a tiny Parquet with two rows: one uses '47.11B' (dotted),
        # the other uses '4711B' (no-dot format sometimes used in older dumps).
        rows_data = [
            {
                "siret": "11111111111111",
                "activitePrincipaleEtablissement": "47.11B",
                "etatAdministratifEtablissement": "A",
            },
            {
                "siret": "22222222222222",
                "activitePrincipaleEtablissement": "4711B",
                "etatAdministratifEtablissement": "A",
            },
            {
                "siret": "33333333333333",
                "activitePrincipaleEtablissement": "4751Z",  # non-food no-dot
                "etatAdministratifEtablissement": "A",
            },
        ]
        col_names = list(rows_data[0].keys())
        arrays = {col: pa.array([r.get(col) for r in rows_data], type=pa.string()) for col in col_names}
        table = pa.table(arrays)
        parquet_path = tmp_path / "test_ape_norm.parquet"
        pq.write_table(table, str(parquet_path), row_group_size=50)

        rows = list(
            stream_etablissements(
                parquet_path,
                ape_whitelist=["47.11B"],
                include_closed=True,
            )
        )
        sirets = [r["siret"] for r in rows]
        assert "11111111111111" in sirets, "Dotted form '47.11B' must match"
        assert "22222222222222" in sirets, "No-dot form '4711B' must match"
        assert "33333333333333" not in sirets, "Non-food no-dot '4751Z' must NOT match"
